apiVersion: v1
kind: Service
metadata:
  name: simple-node
spec:
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP

  selector:
    app.kubernetes.io/name: simple-node
    app.kubernetes.io/instance: simple-node